import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
    sectionContainer: {
      backgroundColor: '#353B51',
      height: '100%',
      alignItems: 'center',
      flex: 1,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '600',
      color: 'white',
      marginTop: 5,
      paddingBottom: 650,
    },
    imageLogo: {
      width: 100,
      height: 100,
      resizeMode: 'contain',
      justifyContent: 'center',
    },
    imageStyle: {
      width: '80%',
      height: '35%',
      position: 'absolute',
      top: 100,
    },
    containTitle: {
      height: '100%',
      position: 'absolute',
      color: 'white',
      top: 400,
      fontSize: 18,
      lineHeight: 24,
      textAlign: 'center',
    },
    boldText: {
      fontWeight: 'bold',
      fontSize: 24,
    },
    buttonLogin: {
      backgroundColor: '#CCEBFC',
      padding: 20,
      marginTop: 100,
      borderRadius: 10,
      position: 'absolute',
      color: 'white',
      top: '55%',
      width: '80%',
    },
    buttonRegister: {
      padding: 20,
      marginTop: 100,
      borderRadius: 10,
      position: 'absolute',
      color: '#CCEBFC',
      top: '65%',
      width: '80%',
      borderWidth: 2,
      borderColor: 'white',
    },
    buttonText: {
      color: 'black',
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    termsText: {
      position: 'absolute',
      color: '#CCEBFC',
      top: '91%',
      width: 350,
      textAlign: 'center',
    },
  });
export default styles;
